package app.expgessia.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Светлая тема в стиле Fallout
val FalloutLightPrimary = Color(0xFF2C5A2C)
val FalloutLightOnPrimary = Color(0xFF8ABB8C)
val FalloutLightPrimaryContainer = Color(0xFFAEDBAA)
val FalloutLightOnPrimaryContainer = Color(0xFF002200)
val FalloutLightSecondary = Color(0xFFA4B6A1)
val FalloutLightOnSecondary = Color(0xFFFFFFFF)
val FalloutLightSecondaryContainer = Color(0xFFD5E8D0)
val FalloutLightOnSecondaryContainer = Color(0xFF101F10)
val FalloutLightTertiary = Color(0xFF38656A)
val FalloutLightOnTertiary = Color(0xFFFFFFFF)
val FalloutLightTertiaryContainer = Color(0xFFBCEBF0)
val FalloutLightOnTertiaryContainer = Color(0xFF002023)
val FalloutLightError = Color(0xFFBA1A1A)
val FalloutLightErrorContainer = Color(0xFFFFDAD6)
val FalloutLightOnError = Color(0xFFFFFFFF)
val FalloutLightOnErrorContainer = Color(0xFF410002)
val FalloutLightBackground = Color(0xFFF8FBF8)
val FalloutLightOnBackground = Color(0xFF191C19)
val FalloutLightSurface = Color(0xFFF8FBF8)
val FalloutLightOnSurface = Color(0xFF191C19)
val FalloutLightSurfaceVariant = Color(0xFFDEE5D9)
val FalloutLightOnSurfaceVariant = Color(0xFF424940)
val FalloutLightOutline = Color(0xFF727970)
val FalloutLightInverseOnSurface = Color(0xFFF0F1EC)
val FalloutLightInverseSurface = Color(0xFF2E312E)
val FalloutLightInversePrimary = Color(0xFF92BF8F)

// Темная тема в стиле Fallout
val FalloutDarkPrimary = Color(0xFF92BF8F)
val FalloutDarkOnPrimary = Color(0xFF003900)
val FalloutDarkPrimaryContainer = Color(0xFF005300)
val FalloutDarkOnPrimaryContainer = Color(0xFFAEDBAA)
val FalloutDarkSecondary = Color(0xFFB9CCB4)
val FalloutDarkOnSecondary = Color(0xFF253424)
val FalloutDarkSecondaryContainer = Color(0xFF3B4B3A)
val FalloutDarkOnSecondaryContainer = Color(0xFFD5E8D0)
val FalloutDarkTertiary = Color(0xFFA0CFD4)
val FalloutDarkOnTertiary = Color(0xFF00363B)
val FalloutDarkTertiaryContainer = Color(0xFF1F4D52)
val FalloutDarkOnTertiaryContainer = Color(0xFFBCEBF0)
val FalloutDarkError = Color(0xFFFFB4AB)
val FalloutDarkErrorContainer = Color(0xFF93000A)
val FalloutDarkOnError = Color(0xFF690005)
val FalloutDarkOnErrorContainer = Color(0xFFFFDAD6)
val FalloutDarkBackground = Color(0xFF111411)
val FalloutDarkOnBackground = Color(0xFFC7D4A8)
val FalloutDarkSurface = Color(0xFF111411)
val FalloutDarkOnSurface = Color(0xFFE1E3DE)
val FalloutDarkSurfaceVariant = Color(0xFF424940)
val FalloutDarkOnSurfaceVariant = Color(0xFFC2C9BD)
val FalloutDarkOutline = Color(0xFF8C9389)
val FalloutDarkInverseOnSurface = Color(0xFF191C19)
val FalloutDarkInverseSurface = Color(0xFFE1E3DE)
val FalloutDarkInversePrimary = Color(0xFF2C5A2C)

